educa/chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'

urlpatterns = [
    path(
        'room/<int:course_id>/',
        views.course_chat_room,
        name='course_chat_room',
    ),
]

educa/educa/urls.py
from courses.views import CourseListView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path(
        'accounts/login/', auth_views.LoginView.as_view(), name='login'
    ),
    path(
        'accounts/logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

educa/students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import course_detail,edit_student_work,delete_student_work,portfolio

from . import views

from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [
    path(
        'register/',
        views.StudentRegistrationView.as_view(),
        name='student_registration',
    ),
    path(
        'enroll-course/',
        views.StudentEnrollCourseView.as_view(),
        name='student_enroll_course',
    ),
    path(
        'courses/',
        views.StudentCourseListView.as_view(),
        name='student_course_list',
    ),
    path(
        'course/<pk>/',
        cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
        name='student_course_detail',
    ),
    path(
        'course/<pk>/<module_id>/',
        cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
        name='student_course_detail_module',
    ),

    path('course/<int:course_id>/', course_detail, name='course_detail'),
    path('course/<int:course_id>/module/<int:module_id>/',course_detail, name='course_detail'),
    path('edit_work/<int:work_id>/',edit_student_work,name='edit_student_work'),
    path('delete_work/<int:work_id>/',delete_student_work,name='delete_student_work'),
    path('/portfolio/',portfolio,name='portfolio'),
   
]

educa/students/models.py
from django.db import models
from courses.models import Subject, Content,Course,Module,ContentType
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template.loader import render_to_string

from courses.fields import OrderField
from django.core.validators import FileExtensionValidator 

# Create your models here.
class StudentWork(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)
    module = models.ForeignKey(Module,on_delete=models.CASCADE)
    content_type = models.CharField(max_length=50)
    content = models.TextField(null= True ,blank=True)
    image = models.ImageField(upload_to = 'uploads/images/',null =True , blank=True, validators=[FileExtensionValidator(['png'])])
    video =models.FileField(upload_to = 'uploads/videos/',null =True , blank=True, validators=[FileExtensionValidator(['mp4'])])
    file = models.FileField(upload_to = 'uploads/files/',null =True , blank=True, validators=[FileExtensionValidator(['pdf'])])
    link = models.URLField(blank=True, null =True)

    def __str__(self):
        return self.title

class ItemBase(models.Model):
   
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(
            f'students/content/{self._meta.model_name}.html',
            {'item': self},
        )


class Text(ItemBase):
    content = models.TextField()


class File(ItemBase):
    file = models.FileField(upload_to='files')


class Image(ItemBase):
    file = models.FileField(upload_to='images')


class Video(ItemBase):
    url = models.URLField()

educa/students/forms.py
from django import forms

from courses.models import Course
from .models import StudentWork


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(
        queryset=Course.objects.none(),
        widget=forms.HiddenInput
    )

    def __init__(self, *args, **kwargs):
        super(CourseEnrollForm, self).__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.all()

class StudentWorkForm(forms.ModelForm):
    class Meta:
        model = StudentWork
        fields =['title','content','image','video','file','link']
        widgets = {
            'image':forms.ClearableFileInput(attrs={'accept':'image/png'}),
            'video':forms.ClearableFileInput(attrs={'accept': 'video/mp4'}),
            'file': forms.ClearableFileInput(attrs={'accept':'application/pdf'}),
        }

educa/students/views.py
from courses.models import Course,Module
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.shortcuts import render,redirect,get_object_or_404

from .forms import CourseEnrollForm,StudentWorkForm
from .models import StudentWork
from django.contrib.auth.decorators import login_required

@login_required
def portfolio(request):
    modules=Module.objects.all()
    if request.user.is_superuser or request.user.groups.filter(name='Instructor').exists():
        student_works = StudentWork.objects.all()
    else:
        student_works = StudentWork.objects.filter(student=request.user)
    modules = Module.objects.all()
    return render(request, 'students/course/portfolio.html',{'modules': modules, 'student_works':student_works})

def course_detail(request,course_id,module_id=None):
        course = get_object_or_404(Course,pk=course_id)
        modules = Module.objects.filter(course=course)
        if module_id:
            selected_module = get_object_or_404(Module,pk=module_id)
        else:
            selected_module = modules.first()
        student_works = StudentWork.objects.filter(module=selected_module)if selected_module else[]
        if request.method == "POST":
            form =StudentWorkForm(request.POST,request.FILES)
            if form.is_valid():
                student_work = form.save(commit=False)
                student_work.module = selected_module
                student_work.save()
                return redirect('course_detail', course_id=course_id,module_id=selected_module.id)
        else:
            form =StudentWorkForm()
        return render(request,'students/course/course_detail.html',{
            'course' :course,
            'modules':modules,
            'selected_module':selected_module,
            'student_works':student_works,
            'form':form
        })
def edit_student_work(request,work_id):
        student_work =get_object_or_404(StudentWork,pk=work_id)
        if(request.method =="POST"):
            form = StudentWorkForm(request.POST,request.FILES,instance=student_work)
            if form.is_valid():
                    form.save()
                    return redirect('course_detail',course_id=student_work.module.course.id,module_id=student_work.module.id)            
        else:
            form = StudentWorkForm(instance=student_work)
        return render(request,'students/course/edit_student_work.html',{
            'form':form,
            'student_work': student_work
        })
    
def delete_student_work(request,work_id):
        student_work = get_object_or_404(StudentWork,pk=work_id)
        Course_id = student_work.module.course.id
        Module_id = student_work.module.id
        student_work.delete()
        return redirect('course_detail',course_id=Course_id,Module_id=Module_id)


class StudentRegistrationView(CreateView):
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(
            username=cd['username'], password=cd['password1']
        )
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'student_course_detail', args=[self.course.id]
        )


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/course/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get course object
        course = self.get_object()
        if 'module_id' in self.kwargs:
            # get current module
            context['module'] = course.modules.get(
                id=self.kwargs['module_id']
            )
        else:
            # get first module
            context['module'] = course.modules.all()[0]
        return context


    

    

educa/students/templates/students/course/course_detail.html
{% extends "base.html" %}
{% load cache %}
{% load static %}

{% block title %}
  {{ object.title }}
{% endblock %}
<head>
    <title> {{course.title}}</title>
    <style>
        #left{
            float:left;
            width:20%;
        }
        #right{
            float:right;
            width:75%;
        }
        .clearfix::after
        {
            content: "";
            clear: both;
            display: table;
        }
    </style>
</head>
{% block content %}

    <div class="clearfix"></div>
        <div id ="left">
            <ul>
                {% for module in modules %}
                    <li>
                        <a href="{%url 'course_detail' course.id module.id %}">{{module.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div id="right" class="module">
            <h2>{{selected_module.title}}</h2>
            <h3> Student Work</h3>
            {% for work in student_works %}
                <div>
                    <p>{{work.content}}</p>
                    {% if work.image %}
                        <img src="{{work.image.url}}" alt="Image" style="max-width:100 px; max-height:100px;">
                    {% endif %}
                    {% if work.video_url %}
                        <a href="{{work.video_url}}" target="_blank">Watch Video </a>
                    {% endif %}
                    {% if work.file %}
                        <a href="{{work.file.url}}" >Download File</a>
                    {% endif %}
                    <a href="{% url 'edit_student_work' work.id %}" > Edit</a>
                    <a href="{% url 'delete_student_work' work.id %}" > Delete</a>
                </div>
            {% endfor %}
            <h3>Upload New Content</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Upload</button>
            </form>
        </div>
    </div>
{% endblock %}

educa/students/templates/students/course/delete_work.html
<!DOCTYPE html>
<html>
<head>
    <title> Delete Student Work </title>
</head>
<body>
    <h2>Delete Student Work</h2>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{work.title}}"?</p>>
        <button type="submit">Delete</button>
    </form>
</body>
</html>

educa/students/templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
  {{ object.title }}
{% endblock %}

{% block content %}
  <h1>
    {{ module.title }}
  </h1>
  <div class="contents">
    <h3>Modules</h3>
    <ul id="modules">
      {% for m in object.modules.all %}
        <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
          <a href="{% url "student_course_detail_module" object.id m.id %}">
            <span>
              Module <span class="order">{{ m.order|add:1 }}</span>
            </span>
            <br>
            {{ m.title }}
          </a>
        </li>
      {% empty %}
        <li>No modules yet.</li>
      {% endfor %}
    </ul>
    <h3>
      <a href="{% url "chat:course_chat_room" object.id %}">
        Course chat room
      </a>
    </h3>
  </div>
  <div class="module">
    {% cache 600 module_contents module %}
      {% for content in module.contents.all %}
        {% with item=content.item %}
          <h2>{{ item.title }}</h2>
          {{ item.render }}
        {% endwith %}
      {% endfor %}
    {% endcache %}
  </div>
{% endblock %}

educa/students/templates/students/course/edit_student_work.html
<!DOCTYPE html>
<html>
<head>
    <title> Edit Student Work </title>
</head>
<body>
    <h2>Edit Student Work</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save</button>
    </form>
</body>
</html>

educa/students/templates/students/course/list.html
{% extends "base.html" %}

{% block title %}My courses{% endblock %}

{% block content %}
  <h1>My courses</h1>
  <div class="module">
    {% for course in object_list %}
      <div class="course-info">
        <h3>{{ course.title }}</h3>
        <p><a href="{% url "student_course_detail" course.id %}">
        Access contents</a></p>
      </div>
    {% empty %}
      <p>
        You are not enrolled in any courses yet.
        <a href="{% url "course_list" %}">Browse courses</a>
        to enroll on a course.
      </p>
    {% endfor %}
  </div>
{% endblock %}

educa/students/templates/students/course/portfolio.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio</title>
    </head>
<body>
    <div>
        <h2>Modules</h2>
        <ul>
            {% for module in modules %}
                <li>{{module.title}}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <h2>Student Work</h2>
        {% for work in student_works %}
            <div>
                <h3>{{ work.title }}</h3>
                <p>{{ work.date }}</p>
                <a href="{% url 'work_detail' work.id %}">{{work.title}}</a> - {{work.date}}"
                {% if request.user == work.student or request.user.is_staff %}
                    <a href="{% url 'edit_work' work.pk %}">Edit</a>"
                    <a href="{% url 'delete_work' work.pk %}">Delete</a>"
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div>
        <h2>Upload student Work</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
    </div>
</body>
</html>

educa/students/templates/students/course/upload_work.html
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio</title>
    </head>
<body>
    <div>
        <h2>Modules</h2>
        <ul>
            {% for module in modules %}
                <li>{{module.title}}</li>
            {% endfor}
        </ul>
    </div>
    <div>
    <h2>Upload student Work</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% form.as_p %}
        <button type="submit">Upload</button>
    </form>
</div>

educa/students/templates/students/course/view_work.html
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio</title>
    </head>
<body>
    <div>
        <h2>Modules</h2>
        <ul>
            {% for module in modules %}
                <li>{{module.title}}</li>
            {% endfor}
        </ul>
    </div>
    <div>
        <h2>Student Work</h2>
        {% for work in student_works %}
            <div>
                <h3>{{ work.title }}</h3>
                <p>{{ work.date }}</p>
                <p>{{ work.content }}</p>
                {% if work.image %}
                    <img src="{{ work.image.url }}" alt="Image">
                {% endif %}
                {% if work.video %}
                    <video controls>
                        <source src="{{ work.video.url }}" type="video/mp4">
                    </video> 
                {% endif %}
                {% if work.file %}
                    <a href="{{ work.file.url}}">Download PDF</a>"
                {% endif %}
                {% if work.link %}
                    <a href="{{ work.link.url}}">External Link</a>"
                {% endif %}                
            </div>
        {% endfor %}
    </div>    
</body>
</html>

educa/students/templates/students/course/work_detail.html
{% extends base.html %}
{% block content %}
    <h1> {{work.title}} </h1>
    <p> {{work.date}}</p>
    <p> {{work.content}}</p>
    {% if work.image %}
        <img src="{{work.image.url}}" alt="{{ work.title}}">
    {% endif %}
    {% if work.video %}
        <video controls>
            <source src="{{work.video.url}}" type="video/mp4">
        </video>
    {% endif %}
    {% if work.file %}
        <a href="{{work.file.url}}">Open PDF</a>
    {% endif %}
    {% if work.link %}
        <a href="{{work.link}}">Related Link</a>
    {% endif %}
    {% endblock %}
    